apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: default
spec:
  ports:
  - port: 16686
    name: ui
  - port: 4318
    name: collector
  clusterIP: None
  selector:
    app: jaeger
