apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger
  namespace: default
spec:
  serviceName: "jaeger"
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: docker.arvancloud.ir/jaegertracing/all-in-one
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 4318
          name: collector
        envFrom:
        - configMapRef:
            name: jaeger-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
