apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
  namespace: default
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/amirox/Desktop/workspace/Extra/Bale-Bootcamp-403/broker-master/containers/cassandra1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

