version: '3.8'

services:
  prometheus:
    image: docker.arvancloud.ir/prom/prometheus
    container_name: prometheus
    networks:
      - broker_net
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"

    volumes:
      - ${PROMETHEUS_PATH}:/etc/prometheus
      - prom_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      - PROMETHEUS_HOST=${PROMETHEUS_HOST}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - APPLICATION_HOST=${APPLICATION_HOST}
      - APPLICATION_PROM_PORT=${APPLICATION_PROM_PORT}
      - NODE_EXPORTER_PORT=${NODE_EXPORTER_PORT}
      
  node_exporter:
    image: docker.arvancloud.ir/prom/node-exporter
    container_name: node_exporter
    networks:
      - broker_net
    ports:
      - ${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT}


  grafana:
    image: docker.arvancloud.ir/grafana/grafana
    container_name: grafana
    networks:
      - broker_net
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - ${GRAFANA_PATH}:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  jaeger:
    image: docker.arvancloud.ir/jaegertracing/all-in-one
    container_name: jaeger
    networks:
      - broker_net
    ports:
      - "${JAEGER_PORT1}:${JAEGER_PORT1}"
      - "${JAEGER_PORT2}:${JAEGER_PORT2}"

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - broker_net
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
  
  cassandra:
    image: cassandra
    container_name: cassandra
    volumes:
      - ${CASSANDRA1_PATH}:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    networks:
      - broker_net
    hostname: ${CASSANDRA_HOSTS}
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER}
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}

  broker:
    image: broker-app-bale
    container_name: broker
    build: .
    env_file:
      - .env.container
    restart: on-failure
    depends_on:
      - postgres
      - cassandra
      - jaeger
      - prometheus
    networks:
      - broker_net

networks:
  broker_net:
    name: broker_net

volumes:
  prom_data: