version: '3'

services:
  prometheus:
    image: docker.arvancloud.ir/prom/prometheus
    container_name: prometheus
    network_mode: "host"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"

    volumes:
      - ${PROMETHEUS_PATH}:/etc/prometheus
      - prom_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      - PROMETHEUS_HOST=${PROMETHEUS_HOST}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - APPLICATION_HOST=${APPLICATION_HOST}
      - APPLICATION_PROM_PORT=${APPLICATION_PROM_PORT}
      - NODE_EXPORTER_PORT=${NODE_EXPORTER_PORT}
      
  node_exporter:
    image: docker.arvancloud.ir/prom/node-exporter
    container_name: node_exporter
    network_mode: "host"
    ports:
      - ${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT}


  grafana:
    image: docker.arvancloud.ir/grafana/grafana
    container_name: grafana
    network_mode: "host"
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - ${GRAFANA_PATH}:/etc/grafana/provisioning/datasources
    # restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  jaeger:
    image: docker.arvancloud.ir/jaegertracing/all-in-one
    container_name: jaeger
    network_mode: "host"
    ports:
      - "${JAEGER_PORT1}:${JAEGER_PORT1}"
      - "${JAEGER_PORT2}:${JAEGER_PORT2}"

  postgres:
    image: postgres
    container_name: postgres
    network_mode: "host"
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data


volumes:
  prom_data: