version: '3.8'

services:
  prometheus:
    image: docker.arvancloud.ir/prom/prometheus
    container_name: prometheus
    network_mode: "host"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"

    volumes:
      - ${PROMETHEUS_PATH}:/etc/prometheus
      - prom_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      - PROMETHEUS_HOST=${PROMETHEUS_HOST}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - APPLICATION_HOST=${APPLICATION_HOST}
      - APPLICATION_PROM_PORT=${APPLICATION_PROM_PORT}
      - NODE_EXPORTER_PORT=${NODE_EXPORTER_PORT}
      


  grafana:
    image: docker.arvancloud.ir/grafana/grafana
    container_name: grafana
    network_mode: "host"
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - ${GRAFANA_PATH}:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  jaeger:
    image: docker.arvancloud.ir/jaegertracing/all-in-one
    container_name: jaeger
    network_mode: "host"
    ports:
      - "${JAEGER_PORT1}:${JAEGER_PORT1}"
      - "${JAEGER_PORT2}:${JAEGER_PORT2}"

  postgres:
    image: docker.arvancloud.ir/library/postgres
    container_name: postgres
    network_mode: "host"
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
  
  cassandra:
    image: docker.arvancloud.ir/library/cassandra
    container_name: cassandra
    volumes:
      - ${CASSANDRA1_PATH}:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    network_mode: "host"
    hostname: ${CASSANDRA_HOSTS}
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER}
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
  
  scylla:
    image: docker.arvancloud.ir/scylladb/scylla
    container_name: scylla
    network_mode: "host"
    ports:
      - "${SCYLLA_PORT1}:${SCYLLA_PORT1}"
      - "${SCYLLA_PORT2}:${SCYLLA_PORT2}"
      - "${SCYLLA_PORT3}:${SCYLLA_PORT3}"
    volumes:
      - ${SCYLLA_PATH}:/var/lib/scylla
    environment:
      - SCYLLA_CLUSTER_NAME=${SCYLLA_CLUSTER}
      - SCYLLA_SEEDS=${SCYLLA_SEED}
      - SCYLLA_API_ADDRESS=${SCYLLA_ADDRESS}
      - SCYLLA_API_PORT=${SCYLLA_PORT3}
      - SCYLLA_PASSWORD_AUTH=true
      - SCYLLA_USERNAME=${SCYLLA_USERNAME}
      - SCYLLA_PASSWORD=${SCYLLA_PASSWORD}
    

      
  # envoy:
  #   image: docker.arvancloud.ir/envoyproxy/envoy:v1.19.1
  #   container_name: envoy
  #   ports:
  #     - "10000:10000"
  #     - "9901:9901"
  #   volumes:
  #     - ./setup/envoy/envoy.yaml:/etc/envoy/envoy.yaml
  #   network_mode: "host"
  #   command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--service-cluster", "envoy"]
  
  # therealbroker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: therealbroker
  #   network_mode: "host"
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - prometheus
  #     - jaeger
  #     - postgres
  #     # - cassandra
  #     # - envoy
  #   restart: on-failure
  #   env_file:
  #     - .env    


volumes:
  prom_data: