apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: default
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/amirox/Desktop/workspace/Extra/Bale-Bootcamp-403/broker-master/containers/prometheus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
